#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
Generate results/chimeric/RESULTS.md from the annotated chimera tables.

Every number in the report is computed here from the pipeline's own output, so the
document can be regenerated after a rerun rather than hand-edited. Procedure and
method rationale live in src/chimeric/README.md; this file is results only.

    python3 src/chimeric/make_report.py --ip SRR30692552 --input SRR30692553
"""

import argparse
import os
import re
import sys

import pandas as pd

# A guide is called enriched when its IP rate exceeds its input rate by this factor,
# after scaling both to chimeras per million trimmed reads. The input library is ~4x
# smaller, so raw counts are not comparable and a pseudocount is needed for guides
# absent from input.
ENRICH_FOLD = 2.0
PSEUDO = 1.0
MIN_IP_CHIMERAS = 3


def read_counts(outdir, uid):
    """Pull per-stage read counts out of the logs the pipeline leaves behind."""
    n = {}
    cut = os.path.join(outdir, f'{uid}.cut.adapt.log')
    if os.path.exists(cut):
        rows = [l.split('\t') for l in open(cut) if l.startswith('OK')]
        if rows:
            n['raw'] = int(rows[0][1])
            n['trimmed'] = int(rows[-1][6])
    for stage, fn in (('after_repeat_mask', f'{uid}.mask.repeat.map.log'),
                      ('after_genome_mask', f'{uid}.mask.genome.map.log')):
        p = os.path.join(outdir, fn)
        if not os.path.exists(p):
            continue
        txt = open(p).read()
        def grab(pat):
            m = re.search(pat + r'\s*\|\s*([0-9.]+)', txt)
            return float(m.group(1)) if m else None
        total = grab(r'Number of input reads')
        uniq = grab(r'Uniquely mapped reads number') or 0
        multi = grab(r'Number of reads mapped to multiple loci') or 0
        if total is not None:
            n[stage.replace('after_', 'input_to_')] = int(total)
            n[stage] = int(total - uniq - multi)
    return n


def load(path):
    if not os.path.exists(path):
        sys.exit(f'missing {path}; run annotate_chimeras.py first')
    df = pd.read_csv(path, sep='\t', low_memory=False)
    for c in ('target_in_repeat', 'target_in_source_locus'):
        if c in df.columns:
            df[c] = df[c].astype("object").where(df[c].notna(), False).astype(bool)
        else:
            df[c] = False
    return df


def _fmt_col(series):
    """Format one column, respecting its dtype.

    Formatting must happen per column, not per row: iterrows() collapses each row to a
    single Series and upcasts a mixed-dtype frame to float, which renders counts as
    "13,759.00".
    """
    if pd.api.types.is_integer_dtype(series):
        return series.map(lambda v: f'{v:,}')
    if pd.api.types.is_float_dtype(series):
        return series.map(lambda v: '' if pd.isna(v) else f'{v:,.2f}'.rstrip('0').rstrip('.'))
    return series.map(lambda v: '' if pd.isna(v) else str(v))


def md_table(df, index_name=''):
    """Render a DataFrame as a GitHub markdown table."""
    df = df.copy()
    df.index.name = index_name or df.index.name or ''
    body = pd.DataFrame({c: _fmt_col(df[c]) for c in df.columns}, index=df.index)
    head = [str(df.index.name)] + [str(c) for c in df.columns]
    lines = ['| ' + ' | '.join(head) + ' |',
             '|' + '|'.join(['---'] * len(head)) + '|']
    for idx in body.index:
        lines.append('| ' + ' | '.join([str(idx)] + list(body.loc[idx])) + ' |')
    return '\n'.join(lines)


def crosstab(df, label):
    ct = pd.crosstab(df['guide_class'], df['target_class'])
    for c in ('rRNA', 'snRNA', 'tRNA', 'hg38'):
        if c not in ct.columns:
            ct[c] = 0
    ct = ct[['hg38', 'rRNA', 'snRNA', 'tRNA']]
    ct['total'] = ct.sum(axis=1)
    ct.loc['all'] = ct.sum()
    return f'**{label}**\n\n' + md_table(ct, 'guide class')


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('--ip', default='SRR30692552')
    p.add_argument('--input', dest='inp', default='SRR30692553')
    p.add_argument('--resdir', default='results/chimeric')
    p.add_argument('--published', default='data/DKC1_IP.snoRNA.hg19.chimeras.csv')
    p.add_argument('--out', default='results/chimeric/RESULTS.md')
    a = p.parse_args()

    ip = load(os.path.join(a.resdir, f'{a.ip}.annotated.tsv'))
    ctrl = load(os.path.join(a.resdir, f'{a.inp}.annotated.tsv'))
    n_ip = read_counts(os.path.join(a.resdir, a.ip), a.ip)
    n_ct = read_counts(os.path.join(a.resdir, a.inp), a.inp)

    o = []
    o.append('# AluACA-guided chimeric reads in DKC1 chimeric eCLIP (hg38)\n')
    o.append('Generated by `src/chimeric/make_report.py` from the pipeline output; '
             're-run it after any rerun rather than editing numbers here. '
             'The procedure, the reference build and every deviation from upstream '
             'are documented in [`src/chimeric/README.md`](../../src/chimeric/README.md).\n')

    o.append('## Samples\n')
    samp = pd.DataFrame({
        'role': ['IP', 'input (background control)'],
        'GSM': ['GSM8521923', 'GSM8521922'],
        'raw reads': [n_ip.get('raw', 0), n_ct.get('raw', 0)],
        'after trimming': [n_ip.get('trimmed', 0), n_ct.get('trimmed', 0)],
        'after repeat+genome masking': [n_ip.get('after_genome_mask', 0),
                                        n_ct.get('after_genome_mask', 0)],
    }, index=[a.ip, a.inp])
    o.append(md_table(samp, 'run'))
    o.append('\nMasking keeps only reads that fail to align end-to-end to both the RepBase '
             'human consensus set and hg38 — that is the pipeline\'s definition of a '
             'candidate chimera, since a read from one contiguous transcript aligns in full '
             'and is dropped here.\n')

    o.append('## Chimeras by guide class and target\n')
    o.append(crosstab(ip, f'{a.ip} — IP'))
    o.append('')
    o.append(crosstab(ctrl, f'{a.inp} — input'))
    o.append('\n`guide_class` is decided by exact membership of the 765 AluACA union names, '
             'not by identifier pattern: 92 names in `snoRNA.txt.fa` also begin `id3` and a '
             'prefix test miscounts them as AluACA. `ambiguous` means a read\'s equal-scoring '
             'guides span both catalogues.\n')

    # ---- enrichment by guide class -----------------------------------------
    # This is the load-bearing comparison in the whole report: DKC1 is the H/ACA
    # pseudouridine synthase, so canonical snoRNA chimeras enriching in the IP is the
    # positive control, and whether AluACA chimeras do the same is the actual question.
    scale_ip = (n_ip.get('trimmed') or 1) / 1e6
    scale_ct = (n_ct.get('trimmed') or 1) / 1e6
    o.append('## IP enrichment by guide class\n')
    rows = {}
    for cls in ('AluACA', 'snoRNA', 'ambiguous'):
        i, c = int((ip.guide_class == cls).sum()), int((ctrl.guide_class == cls).sum())
        rows[cls] = [i, c, i / scale_ip, c / scale_ct,
                     (i / scale_ip) / (c / scale_ct) if c else float('inf')]
    ti, tc_ = len(ip), len(ctrl)
    rows['all'] = [ti, tc_, ti / scale_ip, tc_ / scale_ct,
                   (ti / scale_ip) / (tc_ / scale_ct) if tc_ else float('inf')]
    enr = pd.DataFrame.from_dict(
        rows, orient='index',
        columns=['IP', 'input', 'IP per M', 'input per M', 'fold IP/input'])
    # Keep the raw counts integral; .round() alone would render them as 13,759.00.
    enr['IP'] = enr['IP'].astype(int)
    enr['input'] = enr['input'].astype(int)
    for c in ('IP per M', 'input per M'):
        enr[c] = enr[c].round(1)
    enr['fold IP/input'] = enr['fold IP/input'].round(2)
    o.append(md_table(enr, 'guide class'))

    alu_f = rows['AluACA'][4]
    sno_f = rows['snoRNA'][4]
    o.append(f"""
**Canonical snoRNA-guided chimeras enrich {sno_f:.1f}x in the IP. AluACA-guided chimeras
do not enrich at all ({alu_f:.2f}x) -- they are marginally *depleted*.**

DKC1 is the H/ACA pseudouridine synthase, so the snoRNA number is the positive control
and it behaves exactly as it should. Against that control, the AluACA population in this
dataset does not look DKC1-associated: it is present at a similar or slightly lower rate
in the input, which is what a background population looks like.

The two classes are counted from the same two libraries with the same denominator, so
the {sno_f / alu_f:.0f}x gap between them does not depend on getting the normalisation
right -- any error in the denominator cancels in the comparison. That matters here,
because the libraries did not trim alike ({100 * (n_ip.get('trimmed', 0) / max(n_ip.get('raw', 1), 1)):.0f}%
of IP reads survived trimming versus {100 * (n_ct.get('trimmed', 0) / max(n_ct.get('raw', 1), 1)):.0f}%
of input reads), so absolute per-million rates carry real uncertainty while the
class-vs-class contrast does not.

Everything below therefore describes a population that is, in aggregate, not enriched by
the pull-down. Individual guides may still be real -- {'{n_enr}'} of them do clear the
per-guide enrichment bar -- but the AluACA-mRNA counts in the later sections should be
read as candidates awaiting an orthogonal test, not as established DKC1-dependent
interactions.
""")

    # ---- AluACA detail -----------------------------------------------------
    alu_ip = ip[ip.guide_class == 'AluACA']
    alu_ct = ctrl[ctrl.guide_class == 'AluACA']
    o.append('## AluACA-guided chimeras\n')
    o.append(f'**{len(alu_ip):,}** in the IP, **{len(alu_ct):,}** in the input.\n')

    gi = alu_ip['guide_names'].value_counts()
    gc = alu_ct['guide_names'].value_counts()
    guides = pd.DataFrame({'IP': gi, 'input': gc}).fillna(0).astype(int)
    guides['IP per M'] = guides['IP'] / scale_ip
    guides['input per M'] = guides['input'] / scale_ct
    guides['fold'] = ((guides['IP'] / scale_ip + PSEUDO) /
                      (guides['input'] / scale_ct + PSEUDO))
    guides['IP-enriched'] = ((guides['fold'] >= ENRICH_FOLD) &
                             (guides['IP'] >= MIN_IP_CHIMERAS)).map({True: 'yes', False: ''})
    guides = guides.sort_values('IP', ascending=False)
    n_enr = (guides['IP-enriched'] == 'yes').sum()
    o.append(f'{len(guides):,} distinct AluACA guides carry at least one chimera in the IP; '
             f'**{n_enr:,}** are IP-enriched (>= {ENRICH_FOLD:g}x over input per million '
             f'trimmed reads, with >= {MIN_IP_CHIMERAS} IP chimeras).\n')
    o = [x.replace('{n_enr}', str(n_enr)) if isinstance(x, str) else x for x in o]
    o.append('Top 25 by IP chimera count:\n')
    o.append(md_table(guides.head(25).round(2), 'AluACA guide'))
    o.append('')

    # ---- targets -----------------------------------------------------------
    o.append('## What the AluACA guides pair with\n')
    tc = pd.DataFrame({'IP': alu_ip['target_class'].value_counts(),
                       'input': alu_ct['target_class'].value_counts()}).fillna(0).astype(int)
    o.append(md_table(tc, 'target class'))
    o.append('')

    g_ip = alu_ip[alu_ip.target_class == 'hg38']
    if not g_ip.empty and 'gene_type' in g_ip.columns:
        o.append('### Genomic arm biotypes (IP)\n')
        bt = g_ip['gene_type'].value_counts().head(12).to_frame('chimeras')
        o.append(md_table(bt, 'gene_type'))
        o.append('')

        mrna = g_ip[g_ip.gene_type.astype(str).str.contains('protein_coding', na=False)]
        mrna_ct = pd.DataFrame()
        g_ct = alu_ct[alu_ct.target_class == 'hg38']
        if not g_ct.empty and 'gene_type' in g_ct.columns:
            mrna_ct = g_ct[g_ct.gene_type.astype(str).str.contains('protein_coding', na=False)]
        o.append('## AluACA-mRNA chimeras\n')
        o.append(f'**{len(mrna):,}** IP chimeras have a protein_coding genomic arm '
                 f'({len(mrna_ct):,} in input).\n')
        if not mrna.empty:
            feat = pd.DataFrame({'IP': mrna['feature'].value_counts()})
            if len(mrna_ct):
                feat['input'] = mrna_ct['feature'].value_counts()
            feat = feat.fillna(0).astype(int)
            o.append(md_table(feat, 'feature'))
            o.append('\n**Exonic hits are the defensible set.** An intronic hit is as easily '
                     'explained by co-transcriptional proximity in the host pre-mRNA as by a '
                     'guide-target duplex, so intronic and exonic counts should not be pooled.\n')
            ex = mrna[mrna.feature == 'exonic']
            if not ex.empty:
                top = ex['gene_name'].value_counts().head(25).to_frame('exonic chimeras')
                o.append('Top exonic mRNA targets (IP):\n')
                o.append(md_table(top, 'gene'))
                o.append('')
            pairs = (mrna.assign(pair=mrna['guide_names'] + ' -> ' + mrna['gene_name'].astype(str))
                     ['pair'].value_counts().head(20).to_frame('chimeras'))
            o.append('Top AluACA-mRNA pairs (IP, exonic and intronic):\n')
            o.append(md_table(pairs, 'guide -> gene'))
            o.append('')

    # ---- caveats -----------------------------------------------------------
    o.append('## How much of this survives scrutiny\n')
    rep = alu_ip['target_in_repeat'].sum()
    src = alu_ip['target_in_source_locus'].sum()
    gtot = len(g_ip) if not g_ip.empty else 0
    o.append(f'Of {gtot:,} AluACA chimeras with a genomic arm:\n')
    o.append(f'- **{rep:,} ({100*rep/gtot:.1f}%)** have that arm inside an annotated repeat. '
             'Every AluACA is Alu-derived and hg38 holds over a million Alu copies, so '
             'Alu-to-Alu pairing is the dominant false-positive mode for this question. '
             'These are flagged, not removed.\n' if gtot else '')
    o.append(f'- **{src:,} ({100*src/gtot:.1f}%)** land on a guide locus on the same strand, '
             'i.e. probably one contiguous transcript rather than a chimera.\n' if gtot else '')
    clean = g_ip[~g_ip.target_in_repeat & ~g_ip.target_in_source_locus]
    o.append(f'\nDropping both flags leaves **{len(clean):,}** AluACA genomic chimeras.')
    if not clean.empty and 'gene_type' in clean.columns:
        cm = clean[clean.gene_type.astype(str).str.contains('protein_coding', na=False)]
        ce = cm[cm.feature == 'exonic']
        o.append(f' Of those, **{len(cm):,}** are protein_coding and **{len(ce):,}** '
                 f'are exonic — the most conservative AluACA-mRNA set.\n')
        if not ce.empty:
            o.append('\nConservative AluACA-mRNA set, top genes:\n')
            o.append(md_table(ce['gene_name'].value_counts().head(20).to_frame('chimeras'), 'gene'))

    # ---- sanity check against the published run ----------------------------
    if os.path.exists(a.published):
        pub = sum(1 for _ in open(a.published)) - 1
        ours = int((ip.target_class == 'hg38').sum())
        o.append('\n## Cross-check against the published hg19 run\n')
        o.append(f'The published output for this same sample '
                 f'(`{os.path.basename(a.published)}`, hg19, plain 1951-record snoRNA source) '
                 f'holds **{pub:,}** genomic chimeras. This rerun (hg38, merged '
                 f'2701-record source) gives **{ours:,}**.\n')
        o.append('\nExact agreement is not expected: different genome build, a source '
                 'catalogue with 765 extra sequences competing for the same reads, and a '
                 'repeat-masking index built from public RepBase rather than the lab\'s '
                 'own. Preprocessing, however, was validated to reproduce 4983/5000 '
                 '(99.66%) of the published trimmed sequences byte-for-byte, so any '
                 'divergence is downstream of read handling.\n')

    o.append('\n## Files\n')
    o.append(f'- `{a.resdir}/{a.ip}.annotated.tsv` — one row per IP chimera, all columns\n'
             f'- `{a.resdir}/{a.inp}.annotated.tsv` — same for the input control\n'
             f'- `{a.resdir}/<uid>/<uid>.snoRNA.<target>.chimeras.csv` — per-target, '
             'pipeline-native\n'
             f'- `{a.resdir}/<uid>/<uid>.snorna.chimeras.pipeline.sh` — every command run, '
             'with literal arguments\n'
             f'- `{a.resdir}/<uid>/map.metric.and.log` — per-stage mapping metrics\n')

    os.makedirs(os.path.dirname(a.out), exist_ok=True)
    with open(a.out, 'w') as f:
        f.write('\n'.join(o) + '\n')
    print(f'wrote {a.out}')


if __name__ == '__main__':
    main()
